### ISSUE TITLE
Transient test failures in SupervisorTest

### ISSUE THREAD

**Issue by JayH5** [praekeltfoundation/relay#94]
```
  1) test when the Publisher exits everything is restarted (Relay.SupervisorTest)
     test/relay/supervisor_test.exs:281
     Assertion with == failed
     code:  assert resources |> Enum.map(fn any_res -> Cluster.decode(any_res.value()) end) == clusters
     left:  []
     right: [%Envoy.Api.V2.Cluster{alt_stat_name: "", circuit_breakers: nil, cleanup_interval: nil, common_http_protocol_options: nil, common_lb_config: nil, connect_timeout: %Google.Protobuf.Duration{nanos: 0, seconds: 5}, dns_lookup_family: 0, dns_refresh_rate: nil, dns_resolvers: [], eds_cluster_config: %Envoy.Api.V2.Cluster.EdsClusterConfig{eds_config: %Envoy.Api.V2.Core.ConfigSource{config_source_specifier: {:api_config_source, %Envoy.Api.V2.Core.ApiConfigSource{api_type: 2, cluster_names: [], grpc_services: [%Envoy.Api.V2.Core.GrpcService{credentials: [], initial_metadata: [], target_specifier: {:google_grpc, %Envoy.Api.V2.Core.GrpcService.GoogleGrpc{config: nil, ssl_credentials: nil, stat_prefix: "xds_cluster", target_uri: "127.0.0.1:5000"}}, timeout: nil}], refresh_delay: nil}}}, service_name: "/mc2_0"}, health_checks: [], hosts: [], http2_protocol_options: nil, http_protocol_options: nil, lb_config: nil, lb_policy: 0, lb_subset_config: nil, max_requests_per_connection: nil, metadata: nil, name: "/mc2_0", outlier_detection: nil, per_connection_buffer_limit_bytes: nil, protocol_selection: 0, tls_context: nil, transport_socket: nil, type: 3, upstream_bind_config: nil}]
     stacktrace:
       test/relay/supervisor_test.exs:174: Relay.SupervisorTest.assert_example_response/0
       test/relay/supervisor_test.exs:307: (test)
```

**Comment by JayH5** [comment]
A more recent one:
```
1) test SubSupervisor restart behaviour (Relay.SupervisorTest)
     test/relay/supervisor_test.exs:355
     Expected Elixir.Relay.Supervisor.SubSupervisor (#PID<0.5100.0>) to be alive
     code: assert capture_log(fn ->
     stacktrace:
       (elixir) lib/enum.ex:765: Enum."-each/2-lists^foreach/1-0-"/2
       (elixir) lib/enum.ex:765: Enum.each/2
       test/relay/supervisor_test.exs:335: Relay.SupervisorTest.confirm_process_restarts/2
       test/relay/supervisor_test.exs:363: anonymous fn/0 in Relay.SupervisorTest."test SubSupervisor restart behaviour"/1
       (ex_unit) lib/ex_unit/capture_log.ex:78: ExUnit.CaptureLog.capture_log/2
       test/relay/supervisor_test.exs:362: (test)
```
